"""created fk from dishes to receipts

Revision ID: 40f7264709ea
Revises: d45758a8f84e
Create Date: 2026-03-27 10:24:51.320940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f7264709ea'
down_revision: Union[str, Sequence[str], None] = 'd45758a8f84e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('receipt_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'dishes', 'receipts', ['receipt_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dishes', type_='foreignkey')
    op.drop_column('dishes', 'receipt_id')
    # ### end Alembic commands ###
